VIETNAMESE_BANKS = [
    "Vietcombank (VCB)",
    "VietinBank (CTG)",
    "BIDV (BID)",
    "Agribank",
    "Techcombank (TCB)",
    "MB Bank (MBBank)",
    "ACB",
    "Sacombank",
    "VPBank",
    "TPBank",
    "VIB",
    "HDBank",
    "Eximbank",
    "SCB",
    "OCB",
    "SHB",
    "SeABank",
    "Bac A Bank",
    "OceanBank",
    "PVcomBank",
    "Nam A Bank",
    "NCB",
    "LienVietPostBank",
    "SaigonBank",
    "VietBank",
    "ABBANK",
    "KienlongBank",
    "BaoViet Bank",
    "Public Bank Vietnam",
    "UOB Vietnam",
    "HSBC Vietnam",
    "Standard Chartered Vietnam",
]
